Career Page
baimurzin/cabinet pull request #3
Opened 2018-09-12 15:06 UTC by ADYakovlev

Career page and vacancy page

2018-09-12 19:35 UTC, baimurzin requested changes

2018-09-12 19:35 UTC, baimurzin commented on src/main/resources/templates/career.ftl
> +            <li><a href="vacancy?id=${careerModel.getVacancy(0).getVacancyId()}">${careerModel.getVacancy(0).getCompanyName()} ${careerModel.getVacancy(0).getPositionName()} ${careerModel.getVacancy(
А если у тебя будет 100 вакансий, или 500 или 347

2018-09-12 19:35 UTC, baimurzin commented on src/main/java/org/itlabel/cabinet/controller/StudentCareerController.java
> +            new Vacancy(0, "Google", "middle Java Developer", 250000,1),
Вместо обычного массива используй List list = new ArrayList<>()

2018-09-12 19:35 UTC, baimurzin commented on src/main/java/org/itlabel/cabinet/controller/StudentCareerController.java
> +    public ModelAndView greeting(@RequestParam(value="id", defaultValue="2") Integer id) {
не надо default value 
 у тебя не всегда может быть объект с заранее заданным айди

2018-09-12 19:35 UTC, baimurzin commented on src/main/java/org/itlabel/cabinet/model/CareerModel.java
> +    private Vacancy[] vacancies;
Используй List, ArrayList
У Алексея есть видео лекция по работе с freemarker и spring mvc, можешь посомтреть его 8 урок, там многие моменты увидишь

2018-09-12 19:35 UTC, baimurzin commented on src/main/resources/templates/career.ftl
> +            <li>${careerModel.getUser().getSkills(0)}</li>
итерируй в цикле выводи

2018-09-12 20:57 UTC, somenonename commented
После того как закончил разработку, можешь выделить все свои файлы в которые вносил изменения и сделать форматирование кода (ctrl+alt+L), так код будет понятнее и читаемость увеличится
[Java code style](https://google.github.io/styleguide/javaguide.html)

2018-09-12 21:50 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/controller/StudentCareerController.java
> +            new Vacancy(0, "Google", "middle Java Developer", 250000,1),
Соглашусь.
Массив имеет ограничения - нельзя изменить его размер.
Поэтому пользуйся коллекциями.

2018-09-12 22:29 UTC, Taler777 commented
`public class User {

    private String name;

    private String[] skills;
`
Для скилзов тоже используй коллекции.
Ты же не знаешь сколько навыков будет изначально, а по мере роста опыта навыки будут добавляться.

2018-09-14 00:15 UTC, Taler777 requested changes
Верни ссылки на My profile, добавь сеттер, используй коллекции.
(тестирую request changes)

2018-09-14 00:15 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/model/Vacancy.java
> +public class Vacancy {
Нет сеттера на VacancyDescription
Еще нет VacancyDescription в конструкторе - его там может и не быть, но мало ли.
Можно предусмотреть создание вакансии с частично заполненными данными - тогда надо сделать несколько конструкторов.

2018-09-14 00:15 UTC, Taler777 commented on src/main/resources/templates/level.ftl
> -<a href="profile">My profile</a>
А зачем ты удалил ссылку на страницу My profile ?
Верни ее назад.

2018-09-14 00:15 UTC, Taler777 commented on src/main/resources/templates/chat.ftl
> -<a href="profile">My profile</a>
А зачем ты удалил ссылку на страницу My profile ?
Верни ее назад.

2018-09-14 00:15 UTC, Taler777 commented on src/main/resources/templates/tasks.ftl
> -<a href="profile">My profile</a>
А зачем ты удалил ссылку на страницу My profile ?
Верни ее назад.

2018-09-14 00:15 UTC, Taler777 commented on src/main/resources/templates/vacancy.ftl
> +<a href="level">My level</a>
Здесь было бы неплохо тоже видеть ссылку на страницу My profile ?
Добавь.

2018-09-14 16:22 UTC, Taler777 approved these changes

2018-09-15 17:56 UTC, somenonename approved these changes

2018-09-15 20:46 UTC, baimurzin requested changes

2018-09-15 20:46 UTC, baimurzin commented on src/main/resources/templates/vacancy.ftl
> +<script src="/js/main.js"></script>
Не подключай js по середине body, либо в head либо перед закрытием body.
Если не знаешь почему или интересно пиши - расскажу(собственно это касается ко всем комментариям в ревью)

2018-09-15 20:46 UTC, baimurzin commented on src/main/resources/templates/vacancy.ftl
> +<div style="margin:20px;">
По хорошему лучше выносить в файл стилей css. Но сейчас можешь и так оставить если не хочешь переносить

2018-09-15 20:46 UTC, baimurzin commented on src/main/resources/templates/career.ftl
> +<script src="/js/main.js"></script>
тоже самое

2018-09-15 20:46 UTC, baimurzin commented on src/main/resources/templates/career.ftl
> +            <li><a href="vacancy?id=${vacancy.getVacancyId()}">${vacancy.getCompanyName()} ${vacancy.getPositionName()} ${vacancy.getSalary()} руб/мес</a></li>
сделай vacancy/{id} path вместо get param
ид сразу после слэша

2018-09-17 19:00 UTC, baimurzin requested changes

2018-09-17 19:00 UTC, baimurzin commented on src/main/resources/templates/career.ftl
> +    <link href="/css/main.css" rel="stylesheet"
закрыть тэг

2018-09-18 09:58 UTC, baimurzin approved these changes

2018-09-18 09:58 UTC, merged