Student cab alexeys
baimurzin/cabinet pull request #4
Opened 2018-09-12 21:16 UTC by Taler777

Сделал Кабинет ученика (2)

- Отображения списка заданий
- Переход в задание.
- Управление статусом задания(новый, делается, закончен)

Но пришлось отключить Spring Security

2018-09-12 22:18 UTC, baimurzin requested changes

2018-09-12 22:18 UTC, baimurzin commented on src/main/java/org/itlabel/cabinet/model/Task.java
> +    private int taskId;
вместо примитива используй класс обертку

2018-09-12 22:18 UTC, baimurzin commented on src/main/java/org/itlabel/cabinet/model/Task.java
> +    private String taskName;
Класс уже Task называется, достаточно просто name и тд для всех

2018-09-12 22:18 UTC, baimurzin commented on src/main/resources/templates/task.ftl
> +    <p>Новый статус: <input name="taskStatus" type="text"/></p>
Сделай возможность использования выпадающего списка, там все тоже самое по нейму приходит значение.

2018-09-12 22:18 UTC, baimurzin commented on src/main/resources/templates/task.ftl
> +    <p>Новый статус: <input name="taskStatus" type="text"/></p>
Потому что в инпут можно что угодно ввести

2018-09-13 09:01 UTC, somenonename commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +                    new Task(1, "Набери грибов", "Возьми корзинку, ножик и едь в лес.", "Новое")),
форматирование (ctrl+alt+L)

2018-09-13 09:01 UTC, somenonename commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +    public String showCurrentTaskPage(Model model, @PathVariable("id") int id) {
Лучше использовать Long, т.к. если Integer довольно ограничен для ID

2018-09-13 09:01 UTC, somenonename commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +        model.addAttribute("task", list.get(id - 1));
Почему тут `id - 1`?

2018-09-13 10:05 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/model/Task.java
> +    private int taskId;
> вместо примитива используй класс обертку

Зачем? Почему нельзя использовать примитив?

2018-09-13 10:05 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/model/Task.java
> +    private String taskName;
Принято

2018-09-13 10:07 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +    public String showCurrentTaskPage(Model model, @PathVariable("id") int id) {
Принято.

2018-09-13 10:09 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +        model.addAttribute("task", list.get(id - 1));
Долго объяснять - переделаю.

2018-09-13 10:20 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +    public String showCurrentTaskPage(Model model, @PathVariable("id") int id) {
> Лучше использовать Long, т.к. если Integer довольно ограничен для ID

А в чем ограничение?
Я пока не встречал 2 млрд задач ни на одном ресурсе.

2018-09-13 10:37 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +                    new Task(1, "Набери грибов", "Возьми корзинку, ножик и едь в лес.", "Новое")),
Здесь оно не работает. Переписал немного по-другому.

2018-09-13 11:06 UTC, somenonename commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +    public String showCurrentTaskPage(Model model, @PathVariable("id") int id) {
Дело в том, что если так думать, то в один момент тебя настигнет проблема с тем, что Integer закончился и тебе срочно надо менять код т.к. ничего не работает, а так ты просто берешь огромный запас, который тебя освобождает от необходимости переписывать код в будущем

2018-09-13 11:16 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +    public String showCurrentTaskPage(Model model, @PathVariable("id") int id) {
ок.

2018-09-15 21:03 UTC, baimurzin requested changes

2018-09-15 21:03 UTC, baimurzin commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +        if (status!="") {
https://stackoverflow.com/questions/513832/how-do-i-compare-strings-in-java

ты сейчас сравнил не значение строки, а ссылки объекта СТринг. Допустим у тебя есть строка, которая имеет значение "hello" и ты решил его сравнить
```java
new String("hello") == "hello" // здесь будет false, хотя казалось бы равны строки
```

2018-09-15 21:03 UTC, baimurzin commented on src/main/resources/templates/task.ftl
> +<script src="/js/main.js"></script>
По хорошему лучше выносить в файл стилей css. Но сейчас можешь и так оставить если не хочешь переносить

2018-09-15 21:03 UTC, baimurzin commented on src/main/resources/templates/task.ftl
> +    <select name="status"">
какая-то лишняя кавычка, может сломать верстку, потом искать устанешь, что случилось

2018-09-15 21:03 UTC, baimurzin commented on src/main/resources/templates/tasks.ftl
> +<#if tasks?has_content>
это да, хороший поинт сначала проверять значения

2018-09-16 10:52 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +        if (status!="") {
сделаю equals

2018-09-16 10:52 UTC, Taler777 commented on src/main/resources/templates/task.ftl
> +<script src="/js/main.js"></script>
Взял данный текст из test.ftl

2018-09-16 12:18 UTC, baimurzin requested changes

2018-09-16 12:18 UTC, baimurzin commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +        if (!status.equals("")) {
https://stackoverflow.com/questions/3598770/check-whether-a-string-is-not-null-and-not-empty

2018-09-16 19:07 UTC, baimurzin approved these changes

2018-09-16 21:33 UTC, yakovlevlexandrthirdparty approved these changes

2018-09-17 20:08 UTC, merged