Add db support alexey
baimurzin/cabinet pull request #9
Opened 2018-09-20 13:14 UTC by Taler777

DB support added

2018-09-20 13:19 UTC, somenonename requested changes

2018-09-20 13:19 UTC, somenonename commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +        list.sort((o1, o2) -> {
Сделай сортировку через базу, так будет быстрее

2018-09-20 13:19 UTC, somenonename commented on src/main/java/org/itlabel/cabinet/service/impl/TaskServiceImpl.java
> +    @Transactional
транзакционность для получения данных не нужна

2018-09-20 14:46 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +        list.sort((o1, o2) -> {
Можно с этого места поподробнее, как через базу?

2018-09-20 14:47 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/service/impl/TaskServiceImpl.java
> +    @Transactional
А для других методов?
В JPA уже навешаны аннотации @Transactional. Мне надо их дублировать на методы, изменяющие данные?

2018-09-20 15:15 UTC, somenonename commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +        list.sort((o1, o2) -> {
можешь глянуть как при селекте делать сортировку через “order by”, но в jpa

2018-09-20 15:16 UTC, somenonename commented on src/main/java/org/itlabel/cabinet/service/impl/TaskServiceImpl.java
> +    @Transactional
транзакция нужна только там где данные меняются, так что да, оставь в местах где данные меняются

2018-09-20 15:34 UTC, Taler777 commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +        list.sort((o1, o2) -> {
а, то есть метод сделать кастомный с запросом?

2018-09-20 15:41 UTC, baimurzin commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +        list.sort((o1, o2) -> {
@Taler777 ты можешь добавить просто метод в название которгго будет уже это:
findTasksOrderById();
https://stackoverflow.com/questions/25486583/how-to-use-orderby-with-findall-in-spring-data

2018-09-20 15:42 UTC, baimurzin commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +        list.sort((o1, o2) -> {
@Taler777 либо через query тоже можешь

2018-09-20 15:43 UTC, baimurzin commented on src/main/java/org/itlabel/cabinet/controller/StudentCabinetController.java
> +        list.sort((o1, o2) -> {
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods

2018-09-20 20:39 UTC, somenonename requested changes

2018-09-20 20:39 UTC, somenonename commented on src/main/java/org/itlabel/cabinet/repository/TaskRepository.java
> +@Query(value="select * from tasks order by id", nativeQuery = true)
форматирование слетело

2018-09-20 20:39 UTC, somenonename commented on src/main/java/org/itlabel/cabinet/service/TaskService.java
> +    Task addTask (Task task);
лишний пробел, не забывай про  CTRL+ALT+L

2018-09-20 20:44 UTC, somenonename approved these changes

2018-09-20 21:01 UTC, baimurzin commented on src/main/java/org/itlabel/cabinet/service/impl/TaskServiceImpl.java
>      public List<Task> getAll() {
тут не getAll, когда делаешь getAll код отработает как положено, а тут кастомный запрос с оверхедом сортировкой

2018-09-20 21:12 UTC, baimurzin approved these changes

2018-09-21 10:16 UTC, yakovlevlexandrthirdparty approved these changes

2018-09-21 15:49 UTC, merged